"""
Regenerate geo_ascii.py from GeoJSON source files.
Usage: python geo/_gen_ascii.py
Requires: pip install gj2ascii>=0.4.1
"""
import json
import os

import gj2ascii

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEO_DIR = os.path.join(BASE, 'geo')

# ---- China ----
with open(os.path.join(GEO_DIR, 'china.geojson'), encoding='utf-8') as f:
    china = json.load(f)

CHINA_BBOX = (73.0, 3.0, 136.0, 54.0)
china_features = [f for f in china['features'] if f.get('geometry') and f['geometry'].get('coordinates')]

# Plain # map (backward compat)
china_ascii = gj2ascii.render(china_features, width=80, char='#', fill=' ', bbox=CHINA_BBOX)

# Colored map — each province gets a unique char + grey/muted color
CHARS = [str(i) for i in range(10)] + [chr(ord('a') + i) for i in range(26)]
COLORS = [
    'grey23', 'grey30', 'grey37', 'grey46', 'grey54', 'grey62',
    'grey70', 'grey78', 'grey82', 'grey89',
    'dark_red', 'dark_green', 'dark_blue',
    'dark_magenta', 'dark_cyan', 'dark_yellow',
    'bright_black',
]

pairs = []
china_colormap = {}
for i, feat in enumerate(china_features):
    ch = CHARS[i]
    color = COLORS[i % len(COLORS)]
    pairs.append((feat, ch))
    china_colormap[ch] = color

china_colored_ascii = gj2ascii.render_multiple(
    pairs, width=80, fill=' ', bbox=CHINA_BBOX, all_touched=False
)

# ---- World ----
with open(os.path.join(GEO_DIR, 'world.json'), encoding='utf-8') as f:
    world = json.load(f)

WORLD_BBOX = (-180.0, -90.0, 180.0, 90.0)
world_ascii = gj2ascii.render(
    world['features'], width=80, char='#', fill=' ', bbox=WORLD_BBOX
)

CHINA_PW = 40
CHINA_PH = len(china_ascii.splitlines())
CHINA_COL_PH = len(china_colored_ascii.splitlines())
WORLD_PW = 40
WORLD_PH = len(world_ascii.splitlines())


def write_map_var(lines, name, ascii_str):
    lines.append(name + ' = (')
    raw_lines = ascii_str.splitlines()
    for line in raw_lines:
        escaped = line.replace('\\', '\\\\').replace("'", "\\'")
        lines.append("    '" + escaped + "\\n'")
    lines.append(")")


lines = []
lines.append('# Auto-generated by _gen_ascii.py - do not edit manually')
lines.append('')

lines.append(f'CHINA_BBOX = {CHINA_BBOX!r}')
lines.append(f'WORLD_BBOX = {WORLD_BBOX!r}')
lines.append('MAP_WIDTH = 40  # pixel columns (80 text columns / 2)')
lines.append('')
lines.append(f'CHINA_WIDTH = {CHINA_PW}')
lines.append(f'CHINA_HEIGHT = {CHINA_PH}')
lines.append(f'WORLD_WIDTH = {WORLD_PW}')
lines.append(f'WORLD_HEIGHT = {WORLD_PH}')
lines.append('')

write_map_var(lines, 'CHINA_MAP', china_ascii)
lines.append('')
write_map_var(lines, 'WORLD_MAP', world_ascii)
lines.append('')

# Colored China map
lines.append(f'CHINA_COL_PH = {CHINA_COL_PH}')
lines.append('')
lines.append('CHINA_COLORMAP = {')
for ch, color in sorted(china_colormap.items()):
    lines.append(f"    {ch!r}: {color!r},")
lines.append('}')
lines.append('')
write_map_var(lines, 'CHINA_COLORED', china_colored_ascii)
lines.append('')

lines.append('''
def lonlat_to_rc(lon, lat, bbox, pixel_w, pixel_h):
    x_min, y_min, x_max, y_max = bbox
    cell_size = (x_max - x_min) / pixel_w
    col = int((lon - x_min) / cell_size)
    row = int((y_max - lat) / cell_size)
    col = max(0, min(col, pixel_w - 1))
    row = max(0, min(row, pixel_h - 1))
    return row, col


def plot_on_map(ascii_str, bbox, pixel_w, pixel_h, points):
    rows = [list(r) for r in ascii_str.splitlines()]
    for lon, lat, ch in points:
        r, c = lonlat_to_rc(lon, lat, bbox, pixel_w, pixel_h)
        text_c = c * 2
        if 0 <= r < len(rows) and 0 <= text_c < len(rows[r]):
            rows[r][text_c] = ch
    return '\\n'.join(''.join(r) for r in rows)


def colorize_china(epi_lon, epi_lat, mon_lon, mon_lat):
    from rich.text import Text
    rows = [list(r) for r in CHINA_COLORED.splitlines()]
    ph = len(rows)
    for lon, lat, ch in [(epi_lon, epi_lat, '*'), (mon_lon, mon_lat, '@')]:
        r, c = lonlat_to_rc(lon, lat, CHINA_BBOX, MAP_WIDTH, ph)
        tc = c * 2
        if 0 <= r < ph and 0 <= tc < len(rows[r]):
            rows[r][tc] = ch
    t = Text()
    for line in rows:
        for ch in line:
            if ch == '*':
                t.append('*', style='bold white on red')
            elif ch == '@':
                t.append('@', style='bold white on green')
            elif ch == ' ':
                t.append(' ', style='')
            elif ch in CHINA_COLORMAP:
                t.append(ch, style=CHINA_COLORMAP[ch])
            else:
                t.append(ch, style='dim')
        t.append('\\n')
    return t
''')

output = '\n'.join(lines)

with open(os.path.join(BASE, 'geo', 'geo_ascii.py'), 'w', encoding='utf-8') as f:
    f.write(output)

print('Regenerated geo/geo_ascii.py')
print(f'  China (plain):  {CHINA_PH}x{CHINA_PW}')
print(f'  China (colored): {CHINA_COL_PH}x{CHINA_PW}')
print(f'  World:          {WORLD_PH}x{WORLD_PW}')
