# Auto-generated by _gen_ascii.py - do not edit manually

CHINA_BBOX = (73.0, 3.0, 136.0, 54.0)
WORLD_BBOX = (-180.0, -90.0, 180.0, 90.0)
MAP_WIDTH = 40  # pixel columns (80 text columns / 2)

CHINA_WIDTH = 40
CHINA_HEIGHT = 32
WORLD_WIDTH = 40
WORLD_HEIGHT = 20

CHINA_MAP = (
    '                                                            # # #              \n'
    '                                                            # # # #            \n'
    '                                                          # # # # # #          \n'
    '                # #                                   # # # # # # # # # #      \n'
    '            # # # # #                                       # # # # # # # # #  \n'
    '          # # # # # #                               # # # # # # # # # # # #    \n'
    '          # # # # # # # # #                       # # # # # # # # # # # #      \n'
    '          # # # # # # # # # # # # # #     # # # # # # # # # # # # # # #        \n'
    '    # # # # # # # # # # # # # # # # # # # # # # # # # # # #   # #              \n'
    '# # # # # # # # # # # # # # # # # # # # # # # # # # # #                        \n'
    '  # # # # # # # # # # # # # # # # # # # # # # # # # # # #   #                  \n'
    '    # # # # # # # # # # # # # # # # # # # # # # # # # # # #                    \n'
    '        # # # # # # # # # # # # # # # # # # # # # # # # # #                    \n'
    '        # # # # # # # # # # # # # # # # # # # # # # # # # #                    \n'
    '        # # # # # # # # # # # # # # # # # # # # # # # # # # #                  \n'
    '              # # # # # # # # # # # # # # # # # # # # # # # #                  \n'
    '                # #   # # #     # # # # # # # # # # # # # #                    \n'
    '                                # # # # # # # # # # # # # #                    \n'
    '                                # # # # # # # # # # # # #   #                  \n'
    '                                # # # #   # # # # # # #     #                  \n'
    '                                  #         # # #                              \n'
    '                                                                               \n'
    '                                              #                                \n'
    '                                                                               \n'
    '                                                                               \n'
    '                                                                               \n'
    '                                                                               \n'
    '                                                                               \n'
    '                                                                               \n'
    '                                                                               \n'
    '                                                                               \n'
    '                                                                               \n'
)

WORLD_MAP = (
    '                                                                               \n'
    '            #     # #   # # # # # #                   #       #                \n'
    '    # # # # # # # # # # #   # #             # # # # # # # # # # # # # # # # # #\n'
    '          # # # # #   #               #   #   # # # # # # # # # # # # #        \n'
    '            # # # # # # #               # # # # # # # # # # # # # # # #        \n'
    '            # # # # # #               #     # # # # # # # # # # #              \n'
    '              # # # #                 # # # #   # # # # # # # # # # #          \n'
    '                #                   # # # # # # # # #   # # # # #              \n'
    '                    #               # # # # # # #       #     #                \n'
    '                      # # #               # # # #                              \n'
    '                      # # # # #           # # #               #       #        \n'
    '                        # # # #           # # # # #                 #          \n'
    '                        # # #               # #                   # # # #      \n'
    '                        # #                 #                     # # # #      \n'
    '                        #                                                     #\n'
    '                                                                               \n'
    '                                                                               \n'
    '                        #                         # #     # # # # # # #        \n'
    '        # # # # # # # #           # # # # # # # # # # # # # # # # # # # # #    \n'
    '# # #   # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #\n'
)


def lonlat_to_rc(lon, lat, bbox, pixel_w, pixel_h):
    x_min, y_min, x_max, y_max = bbox
    cell_size = (x_max - x_min) / pixel_w
    col = int((lon - x_min) / cell_size)
    row = int((y_max - lat) / cell_size)
    col = max(0, min(col, pixel_w - 1))
    row = max(0, min(row, pixel_h - 1))
    return row, col


def plot_on_map(ascii_str, bbox, pixel_w, pixel_h, points):
    rows = [list(r) for r in ascii_str.splitlines()]
    for lon, lat, ch in points:
        r, c = lonlat_to_rc(lon, lat, bbox, pixel_w, pixel_h)
        text_c = c * 2
        if 0 <= r < len(rows) and 0 <= text_c < len(rows[r]):
            rows[r][text_c] = ch
    return '\n'.join(''.join(r) for r in rows)
